version: '3'

services:
  mysql:
    image: mariadb/server
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./dockerize/db_data:/var/lib/mysql
#        working_dir: /application
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    ports:
      - "${DB_PORT}:3306"
    networks: 
      - default
  web:
    build: .
    command:
      - ./dockerize/wait-for-it.sh
      - mysql:3306
      - --
      - ./dockerize/run.sh
    volumes:
      - .:/usr/src/app
    ports:
      - "${WEB_PORT}:8000"
    depends_on:
      - mysql
    links:
      - mysql
    networks: 
      - default

networks:
  default:
    driver: bridge
