version: '3'

services:
  mysql:
    image: mariadb/server
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    ports:
      - "${DB_PORT}:3306"
  web:
    build: .
    command:
      - ./dockerize/wait-for-it.sh
      - mysql:3306
      - --
      - ./dockerize/run.sh
    volumes:
      - .:/usr/src/app
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - mysql
    links:
      - mysql