# Generated by Django 3.0.3 on 2020-02-12 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipio', '0001_initial'),
        ('grupo', '0001_initial'),
        ('localidad', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('estado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellidoPaterno', models.CharField(max_length=150)),
                ('apellidoMaterno', models.CharField(max_length=150)),
                ('curp', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=250)),
                ('correo', models.EmailField(max_length=100)),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('whatsapp', models.CharField(max_length=100, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estado.Estado')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo.Grupo')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localidad.Localidad')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipio.Municipio')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacion.Organizacion')),
            ],
        ),
    ]
