# Generated by Django 3.0.3 on 2020-02-26 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='calle_numero',
        ),
    ]
