# Generated by Django 3.0.3 on 2020-02-13 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seccion', '0001_initial'),
        ('persona', '0002_persona_nivel_confianza'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='clave_electoral',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='persona',
            name='seccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seccion.Seccion'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellidoMaterno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellidoPaterno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
