# Generated by Django 3.0.3 on 2020-02-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_remove_persona_calle_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='calle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='numero',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
