# Generated by Django 3.0.3 on 2020-02-13 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seccion', '0001_initial'),
        ('persona', '0003_auto_20200213_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seccion.Seccion'),
        ),
    ]
