<<<<<<< HEAD
# Generated by Django 3.0.3 on 2020-02-13 22:57
=======
# Generated by Django 3.0.3 on 2020-02-13 23:04
>>>>>>> 47c86555c64d3c4817b1bc3166f670d92124e084

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20200213_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='seccion',
        ),
    ]
