# Generated by Django 3.0.3 on 2020-02-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_persona_colonia'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='instagram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='twitter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
