# Generated by Django 3.0.3 on 2020-02-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_remove_persona_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='calle_numero',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='codigo_postal',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='colonia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino')], default=1),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
