# Generated by Django 3.0.3 on 2020-02-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_persona_estructura'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='nota',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
