# Generated by Django 3.0.3 on 2020-02-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_persona_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='seccion_electoral',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
