# Generated by Django 3.0.3 on 2020-02-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_persona_seccion_electoral'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='municipio_text',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellidoMaterno',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellidoPaterno',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='calle',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='clave_electoral',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fechaNacimiento',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
