# Generated by Django 3.0.3 on 2020-02-26 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organismo', '0001_initial'),
        ('estructura', '0001_initial'),
        ('sector', '0001_initial'),
        ('persona', '0009_auto_20200226_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='colonia',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estructura',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.Estructura'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='organismo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organismo.Organismo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sector',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sector.Sector'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
