# Generated by Django 3.0.3 on 2020-02-26 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipio', '0001_initial'),
        ('persona', '0010_auto_20200226_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='municipio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='municipio.Municipio'),
        ),
    ]
