# Generated by Django 3.0.3 on 2020-02-27 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localidad', '0001_initial'),
        ('persona', '0012_auto_20200226_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='localidad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='localidad.Localidad'),
            preserve_default=False,
        ),
    ]
